<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "woehrl_sso_intranet"
 *
 * Auto generated by Extension Builder 2014-07-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Intranet SSO 6.2',
	'description' => 'Single sign-on authentication for frontend user',
	'category' => 'services',
	'author' => 'Alexander Fuchs',
	'author_email' => 'alexander.fuchs@woehrl.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);