<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "woehrl_forum"
 *
 * Auto generated by Extension Builder 2014-10-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Woehrl Forum 6.2',
	'description' => 'Haustrainer Forum die WÖHRL Akademie ',
	'category' => 'plugin',
	'author' => 'Alexander Fuchs',
	'author_email' => 'alexander.fuchs@woehrl.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);