<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "woehrl_rss_feed"
 *
 * Auto generated by Extension Builder 2015-04-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WÖHRL RSS-Feed',
	'description' => 'Einbindung TextilWirtschaft.de Newsticker in die Webseite',
	'category' => 'plugin',
	'author' => 'Alexander Fuchs',
	'author_email' => 'Alexander.Fuchs@woehrl.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);