<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "woehrl_akademie"
 *
 * Auto generated by Extension Builder 2014-07-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WÖHRL Akademie',
	'description' => 'WÖHRL Akademie | Seminare',
	'category' => 'plugin',
	'author' => 'Alexander Fuchs',
	'author_email' => 'alexander.fuchs@woehrl.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'extbase' => '6.2',
			'fluid' => '6.2',
			'tt_address' => '2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);