#
# Extension Builder settings for extension woehrl_seminare
# generated 2012-09-26
#
# See http://www.yaml.org/spec/1.2/spec.html
#

---

###########    Overwrite settings  ###########
#
# These settings only apply, if the roundtrip feature of the extension builder
# is enabled in the extension manager
#
# Usage:
# nesting reflects the file structure
# a setting applies to a file or recursive to all files and subfolders
#
# merge:
# means for classes: All properties ,methods and method bodies
# of the existing class will be modified according to the new settings
# but not overwritten
#
# for locallang xml files: Existing keys and labels are always
# preserved (renaming in the GUI has only influence on the property and method names)
#
# for other files: You will find a Split token at the end of the file
# After this token you can write whatever you want and it will be appended
# everytime the code is generated
#
# keep:
# files are never overwritten
# These settings may break the functionality of the extension builder!
# Handle with care!
#
#

############  extension settings  ##############

overwriteSettings:
  Classes:
    Controller: merge
    Domain:
      Model: keep
      Repository: merge

  Configuration:
    TCA: keep
    TypoScript: merge
    FlexForms: keep

  Resources:
    Private:
      Language:
        #locallang.xml: merge
        locallang.xlf: keep
        locallang_db.xlf: keep
        locallang_csh_tx_woehrlseminare_domain_model_event.xlf: keep
        locallang_csh_tx_woehrlseminare_domain_model_subscriber.xlf: keep
        locallang_csh_tx_woehrlseminare_domain_model_category.xlf: keep
        locallang_csh_tx_woehrlseminare_domain_model_discipline.xlf: keep
      Backend:
        Layouts:
          Default.html: keep
        Event:
          List.html: keep
          BeList.html: keep
      Templates:
        Event:
           List.html: keep
           Show.html: keep
        Subscriber:
           New.html: keep
        Category:
           List.html: keep
      Partials:
        Subscriber:
           FormFields.html: keep

  ext_icon.gif: keep

  ext_localconf.php: merge

  ext_tables.php: keep

#  ext_tables.sql: merge

## ext_autoload.php is only needed in special cases ##
createAutoloadRegistry: false

######### settings for classBuilder #############################
#
# here you may define default parent classes for your classes
# these settings only apply for new generated classes
# you may also just change the parent class in the generated class file.
# It will be kept on next code generation, if the overwrite settings
# are configured to merge it
#
#  Experimental!!
#################################################################

classBuilder:

  Controller:
    parentClass: Tx_Extbase_MVC_Controller_ActionController

  Model:
    AbstractEntity:
      parentClass: Tx_Extbase_DomainObject_AbstractEntity

    AbstractValueObject:
      parentClass: Tx_Extbase_DomainObject_AbstractValueObject

  Repository:
    parentClass: Tx_Extbase_Persistence_Repository
